export const SURAH_NAMES = [
  'الفاتحة',
  'البقرة',
  'اٰل عمرٰن',
  'النّساۤء',
  'الماۤئدة',
  'الانعام',
  'الاعراف',
  'الانفال',
  'التّوبة',
  'يونس',
  'هود',
  'يوسف',
  'الرّعد',
  'ابرٰهيم',
  'الحجر',
  'النّحل',
  'الاسراۤء',
  'الكهف',
  'مريم',
  'طٰهٰ',
  'الانبياۤء',
  'الحجّ',
  'المؤمنون',
  'النّور',
  'الفرقان',
  'الشّعراۤء',
  'النّمل',
  'القصص',
  'العنكبوت',
  'الرّوم',
  'لقمٰن',
  'السّجدة',
  'الاحزاب',
  'سبأ',
  'فاطر',
  'يٰسۤ',
  'الصّٰۤفّٰت',
  'صۤ',
  'الزّمر',
  'غافر',
  'فصّلت',
  'الشّورٰى',
  'الزّخرف',
  'الدّخان',
  'الجاثية',
  'الاحقاف',
  'محمّد',
  'الفتح',
  'الحجرٰت',
  'قۤ',
  'الذّٰريٰت',
  'الطّور',
  'النّجم',
  'القمر',
  'الرّحمٰن',
  'الواقعة',
  'الحديد',
  'المجادلة',
  'الحشر',
  'الممتحنة',
  'الصّفّ',
  'الجمعة',
  'المنٰفقون',
  'التّغابن',
  'الطّلاق',
  'التّحريم',
  'المُلك',
  'القلم',
  'الحاۤقّة',
  'المعارج',
  'نوح',
  'الجنّ',
  'المزّمّل',
  'المدّثّر',
  'القيٰمة',
  'الانسان',
  'المرسلٰت',
  'النّبأ',
  'النّٰزعٰت',
  'عبس',
  'التّكوير',
  'الانفطار',
  'المطفّفين',
  'الانشقاق',
  'البروج',
  'الطّارق',
  'الاعلى',
  'الغاشية',
  'الفجر',
  'البلد',
  'الشّمس',
  'الّيل',
  'الضّحى',
  'الشّرح',
  'التّين',
  'العلق',
  'القدر',
  'البيّنة',
  'الزّلزلة',
  'العٰديٰت',
  'القارعة',
  'التّكاثر',
  'العصر',
  'الهمزة',
  'الفيل',
  'قريش',
  'الماعون',
  'الكوثر',
  'الكٰفرون',
  'النّصر',
  'اللّهب',
  'الاخلاص',
  'الفلق',
  'النّاس',
] as const;

export const SURAH_NAMES_LATIN = [
  'Al-Fātiḥah',
  'Al-Baqarah',
  "Āli 'Imrān",
  "An-Nisā'",
  "Al-Mā'idah",
  "Al-An'ām",
  "Al-A'rāf",
  'Al-Anfāl',
  'At-Taubah',
  'Yūnus',
  'Hūd',
  'Yūsuf',
  "Ar-Ra'd",
  'Ibrāhīm',
  'Al-Ḥijr',
  'An-Naḥl',
  "Al-Isrā'",
  'Al-Kahf',
  'Maryam',
  'Ṭāhā',
  "Al-Anbiyā'",
  'Al-Ḥajj',
  "Al-Mu'minūn",
  'An-Nūr',
  'Al-Furqān',
  "Asy-Syu'arā'",
  'An-Naml',
  'Al-Qaṣaṣ',
  "Al-'Ankabūt",
  'Ar-Rūm',
  'Luqmān',
  'As-Sajdah',
  'Al-Aḥzāb',
  "Saba'",
  'Fāṭir',
  'Yāsīn',
  'Aṣ-Ṣāffāt',
  'Ṣād',
  'Az-Zumar',
  'Gāfir',
  'Fuṣṣilat',
  'Asy-Syūrā',
  'Az-Zukhruf',
  'Ad-Dukhān',
  'Al-Jāṡiyah',
  'Al-Aḥqāf',
  'Muḥammad',
  'Al-Fatḥ',
  'Al-Ḥujurāt',
  'Qāf',
  'Aż-Żāriyāt',
  'Aṭ-Ṭūr',
  'An-Najm',
  'Al-Qamar',
  'Ar-Raḥmān',
  "Al-Wāqi'ah",
  'Al-Ḥadīd',
  'Al-Mujādalah',
  'Al-Ḥasyr',
  'Al-Mumtaḥanah',
  'Aṣ-Ṣaff',
  "Al-Jumu'ah",
  'Al-Munāfiqūn',
  'At-Tagābun',
  'Aṭ-Ṭalāq',
  'At-taḥrīm',
  'Al-Mulk',
  'Al-Qalam',
  'Al-Ḥāqqah',
  "Al-Ma'ārij",
  'Nūḥ',
  'Al-Jinn',
  'Al-Muzzammil',
  'Al-Muddaṡṡir',
  'Al-Qiyāmah',
  'Al-Insān',
  'Al-Mursalāt',
  "An-Naba'",
  "An-Nāzi'āt",
  "'Abasa",
  'At-Takwīr',
  'Al-Infiṭār',
  'Al-Muṭaffifīn',
  'Al-Insyiqāq',
  'Al-Burūj',
  'Aṭ-Ṭāriq',
  "Al-A'lā",
  'Al-Gāsyiyah',
  'Al-Fajr',
  'Al-Balad',
  'Asy-Syams',
  'Al-Lail',
  'Aḍ-Ḍuḥā',
  'Asy-Syarḥ',
  'At-Tīn',
  "Al-'Alaq",
  'Al-Qadr',
  'Al-Bayyinah',
  'Az-Zalzalah',
  "Al-'Ādiyāt",
  "Al-Qāri'ah",
  'At-Takāṡur',
  "Al-'Aṣr",
  'Al-Humazah',
  'Al-Fīl',
  'Quraisy',
  "Al-Mā'ūn",
  'Al-Kauṡar',
  'Al-Kāfirūn',
  'An-Naṣr',
  'Al-Lahab',
  'Al-Ikhlāṣ',
  'Al-Falaq',
  'An-Nās',
] as const;

export const SURAH_NAMES_ID = [
  'Al-Fatihah',
  'Al-Baqarah',
  "Ali 'Imran",
  "An-Nisa'",
  "Al-Ma'idah",
  "Al-An'am",
  "Al-A'raf",
  'Al-Anfal',
  'At-Taubah',
  'Yunus',
  'Hud',
  'Yusuf',
  "Ar-Ra'd",
  'Ibrahim',
  'Al-Hijr',
  'An-Nahl',
  "Al-Isra'",
  'Al-Kahf',
  'Maryam',
  'Taha',
  "Al-Anbiya'",
  'Al-Hajj',
  "Al-Mu'minun",
  'An-Nur',
  'Al-Furqan',
  "Asy-Syu'ara'",
  'An-Naml',
  'Al-Qasas',
  "Al-'Ankabut",
  'Ar-Rum',
  'Luqman',
  'As-Sajdah',
  'Al-Ahzab',
  "Saba'",
  'Fatir',
  'Yasin',
  'As-Saffat',
  'Sad',
  'Az-Zumar',
  'Gafir',
  'Fussilat',
  'Asy-Syura',
  'Az-Zukhruf',
  'Ad-Dukhan',
  'Al-Jasiyah',
  'Al-Ahqaf',
  'Muhammad',
  'Al-Fath',
  'Al-Hujurat',
  'Qaf',
  'Az-Zariyat',
  'At-Tur',
  'An-Najm',
  'Al-Qamar',
  'Ar-Rahman',
  "Al-Waqi'ah",
  'Al-Hadid',
  'Al-Mujadalah',
  'Al-Hasyr',
  'Al-Mumtahanah',
  'As-Saff',
  "Al-Jumu'ah",
  'Al-Munafiqun',
  'At-Tagabun',
  'At-Talaq',
  'At-tahrim',
  'Al-Mulk',
  'Al-Qalam',
  'Al-Haqqah',
  "Al-Ma'arij",
  'Nuh',
  'Al-Jinn',
  'Al-Muzzammil',
  'Al-Muddassir',
  'Al-Qiyamah',
  'Al-Insan',
  'Al-Mursalat',
  "An-Naba'",
  "An-Nazi'at",
  "'Abasa",
  'At-Takwir',
  'Al-Infitar',
  'Al-Mutaffifin',
  'Al-Insyiqaq',
  'Al-Buruj',
  'At-Tariq',
  "Al-A'la",
  'Al-Gasyiyah',
  'Al-Fajr',
  'Al-Balad',
  'Asy-Syams',
  'Al-Lail',
  'Ad-Duha',
  'Asy-Syarh',
  'At-Tin',
  "Al-'Alaq",
  'Al-Qadr',
  'Al-Bayyinah',
  'Az-Zalzalah',
  "Al-'Adiyat",
  "Al-Qari'ah",
  'At-Takasur',
  "Al-'Asr",
  'Al-Humazah',
  'Al-Fil',
  'Quraisy',
  "Al-Ma'un",
  'Al-Kausar',
  'Al-Kafirun',
  'An-Nasr',
  'Al-Lahab',
  'Al-Ikhlas',
  'Al-Falaq',
  'An-Nas',
] as const;

export const SURAH_NAMES_TRANS_ID = [
  'Pembuka',
  'Sapi',
  'Keluarga Imran',
  'Perempuan',
  'Hidangan',
  'Binatang Ternak',
  'Tempat Tertinggi',
  'Rampasan Perang',
  'Pengampunan',
  'Yunus',
  'Hud',
  'Yusuf',
  'Guruh',
  'Ibrahim',
  'Hijr',
  'Lebah',
  'Memperjalankan di Malam Hari',
  'Gua',
  'Maryam',
  'Taha',
  'Para Nabi',
  'Haji',
  'Orang-Orang Mukmin',
  'Cahaya',
  'Pembeda',
  'Para Penyair',
  'Semut',
  'Kisah-Kisah',
  'Laba-Laba',
  'Romawi',
  'Luqman',
  'Sajdah',
  'Golongan Yang Bersekutu',
  "Saba'",
  'Pencipta',
  'Yasin',
  'Barisan-Barisan',
  'Ṣād',
  'Rombongan',
  'Maha Pengampun',
  'Dijelaskan',
  'Musyawarah',
  'Perhiasan dari Emas',
  'Kabut Asap',
  'Berlutut',
  'Ahqaf',
  'Nabi Muhammad',
  'Kemenangan',
  'Kamar-Kamar',
  'Qaf',
  'Yang Menerbangkan',
  'Gunung',
  'Bintang',
  'Bulan',
  'Yang Maha Pengasih',
  'Hari Kiamat Yang Pasti Terjadi',
  'Besi',
  'Gugatan',
  'Pengusiran',
  'Wanita Yang Diuji',
  'Barisan',
  'Jumat',
  'Orang-Orang Munafik',
  'Pengungkapan Kesalahan',
  'Talak',
  'Pengharaman',
  'Kerajaan',
  'Pena',
  'Hari Kiamat Yang Pasti Terjadi',
  'Tempat-Tempat Naik',
  'Nuh',
  'Jin',
  'Orang Berkelumun',
  'Orang Berselimut',
  'Hari Kiamat',
  'Manusia',
  'Malaikat Yang Diutus',
  'Berita',
  'Yang Mencabut Dengan Keras',
  'Berwajah Masam',
  'Penggulungan',
  'Terbelah',
  'Orang-Orang Yang Curang',
  'Terbelah',
  'Gugusan Bintang',
  'Yang Datang Pada Malam Hari',
  'Yang Maha Tinggi',
  'Hari Kiamat Yang Menghilangkan Kesadaran',
  'Fajar',
  'Negeri',
  'Matahari',
  'Malam',
  'Duha',
  'Pelapangan',
  'Buah Tin',
  'Segumpal Darah',
  'Al-Qadar',
  'Bukti Nyata',
  'Guncangan',
  'Kuda Perang Yang Berlari Kencang',
  "Al-Qāri'ah",
  'Berbangga-Bangga Dalam Memperbanyak Dunia',
  'Masa',
  'Pengumpat',
  'Gajah',
  'Orang Quraisy',
  'Bantuan',
  'Nikmat Yang Banyak',
  'Orang-Orang kafir',
  'Pertolongan',
  'Gejolak Api',
  'Ikhlas',
  'Fajar',
  'Manusia',
] as const;

export const SURAH_CATEGORIES = [
  'Makkiyah',
  'Madaniyah',
  'Madaniyah',
  'Madaniyah',
  'Madaniyah',
  'Makkiyah',
  'Makkiyah',
  'Madaniyah',
  'Madaniyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Madaniyah',
  'Makkiyah',
  'Madaniyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Madaniyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Madaniyah',
  'Madaniyah',
  'Madaniyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Madaniyah',
  'Madaniyah',
  'Madaniyah',
  'Madaniyah',
  'Madaniyah',
  'Madaniyah',
  'Madaniyah',
  'Madaniyah',
  'Madaniyah',
  'Madaniyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Madaniyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Madaniyah',
  'Madaniyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Madaniyah',
  'Makkiyah',
  'Makkiyah',
  'Madaniyah',
  'Madaniyah',
] as const;

export const SURAH_NUM_VERSES = [
  7, 286, 200, 176, 120, 165, 206, 75, 129, 109, 123, 111, 43, 52, 99, 128, 111,
  110, 98, 135, 112, 78, 118, 64, 77, 227, 93, 88, 69, 60, 34, 30, 73, 54, 45,
  83, 182, 88, 75, 85, 54, 53, 89, 59, 37, 35, 38, 29, 18, 45, 60, 49, 62, 55,
  78, 96, 29, 22, 24, 13, 14, 11, 11, 18, 12, 12, 30, 52, 52, 44, 28, 28, 20,
  56, 40, 31, 50, 40, 46, 42, 29, 19, 36, 25, 22, 17, 19, 26, 30, 20, 15, 21,
  11, 8, 8, 19, 5, 8, 8, 11, 11, 8, 3, 9, 5, 4, 7, 3, 6, 3, 5, 4, 5, 6,
] as const;
