export const SURAH_NAMES = [
  'الفاتحة',
  'البقرة',
  'اٰل عمرٰن',
  'النّساۤء',
  'الماۤئدة',
  'الانعام',
  'الاعراف',
  'الانفال',
  'التّوبة',
  'يونس',
  'هود',
  'يوسف',
  'الرّعد',
  'ابرٰهيم',
  'الحجر',
  'النّحل',
  'الاسراۤء',
  'الكهف',
  'مريم',
  'طٰهٰ',
  'الانبياۤء',
  'الحجّ',
  'المؤمنون',
  'النّور',
  'الفرقان',
  'الشّعراۤء',
  'النّمل',
  'القصص',
  'العنكبوت',
  'الرّوم',
  'لقمٰن',
  'السّجدة',
  'الاحزاب',
  'سبأ',
  'فاطر',
  'يٰسۤ',
  'الصّٰۤفّٰت',
  'صۤ',
  'الزّمر',
  'غافر',
  'فصّلت',
  'الشّورٰى',
  'الزّخرف',
  'الدّخان',
  'الجاثية',
  'الاحقاف',
  'محمّد',
  'الفتح',
  'الحجرٰت',
  'قۤ',
  'الذّٰريٰت',
  'الطّور',
  'النّجم',
  'القمر',
  'الرّحمٰن',
  'الواقعة',
  'الحديد',
  'المجادلة',
  'الحشر',
  'الممتحنة',
  'الصّفّ',
  'الجمعة',
  'المنٰفقون',
  'التّغابن',
  'الطّلاق',
  'التّحريم',
  'المُلك',
  'القلم',
  'الحاۤقّة',
  'المعارج',
  'نوح',
  'الجنّ',
  'المزّمّل',
  'المدّثّر',
  'القيٰمة',
  'الانسان',
  'المرسلٰت',
  'النّبأ',
  'النّٰزعٰت',
  'عبس',
  'التّكوير',
  'الانفطار',
  'المطفّفين',
  'الانشقاق',
  'البروج',
  'الطّارق',
  'الاعلى',
  'الغاشية',
  'الفجر',
  'البلد',
  'الشّمس',
  'الّيل',
  'الضّحى',
  'الشّرح',
  'التّين',
  'العلق',
  'القدر',
  'البيّنة',
  'الزّلزلة',
  'العٰديٰت',
  'القارعة',
  'التّكاثر',
  'العصر',
  'الهمزة',
  'الفيل',
  'قريش',
  'الماعون',
  'الكوثر',
  'الكٰفرون',
  'النّصر',
  'اللّهب',
  'الاخلاص',
  'الفلق',
  'النّاس',
] as const;

export const SURAH_NAMES_LATIN = [
  'Al-Fātiḥah',
  'Al-Baqarah',
  "Āli 'Imrān",
  "An-Nisā'",
  "Al-Mā'idah",
  "Al-An'ām",
  "Al-A'rāf",
  'Al-Anfāl',
  'At-Taubah',
  'Yūnus',
  'Hūd',
  'Yūsuf',
  "Ar-Ra'd",
  'Ibrāhīm',
  'Al-Ḥijr',
  'An-Naḥl',
  "Al-Isrā'",
  'Al-Kahf',
  'Maryam',
  'Ṭāhā',
  "Al-Anbiyā'",
  'Al-Ḥajj',
  "Al-Mu'minūn",
  'An-Nūr',
  'Al-Furqān',
  "Asy-Syu'arā'",
  'An-Naml',
  'Al-Qaṣaṣ',
  "Al-'Ankabūt",
  'Ar-Rūm',
  'Luqmān',
  'As-Sajdah',
  'Al-Aḥzāb',
  "Saba'",
  'Fāṭir',
  'Yāsīn',
  'Aṣ-Ṣāffāt',
  'Ṣād',
  'Az-Zumar',
  'Gāfir',
  'Fuṣṣilat',
  'Asy-Syūrā',
  'Az-Zukhruf',
  'Ad-Dukhān',
  'Al-Jāṡiyah',
  'Al-Aḥqāf',
  'Muḥammad',
  'Al-Fatḥ',
  'Al-Ḥujurāt',
  'Qāf',
  'Aż-Żāriyāt',
  'Aṭ-Ṭūr',
  'An-Najm',
  'Al-Qamar',
  'Ar-Raḥmān',
  "Al-Wāqi'ah",
  'Al-Ḥadīd',
  'Al-Mujādalah',
  'Al-Ḥasyr',
  'Al-Mumtaḥanah',
  'Aṣ-Ṣaff',
  "Al-Jumu'ah",
  'Al-Munāfiqūn',
  'At-Tagābun',
  'Aṭ-Ṭalāq',
  'At-taḥrīm',
  'Al-Mulk',
  'Al-Qalam',
  'Al-Ḥāqqah',
  "Al-Ma'ārij",
  'Nūḥ',
  'Al-Jinn',
  'Al-Muzzammil',
  'Al-Muddaṡṡir',
  'Al-Qiyāmah',
  'Al-Insān',
  'Al-Mursalāt',
  "An-Naba'",
  "An-Nāzi'āt",
  "'Abasa",
  'At-Takwīr',
  'Al-Infiṭār',
  'Al-Muṭaffifīn',
  'Al-Insyiqāq',
  'Al-Burūj',
  'Aṭ-Ṭāriq',
  "Al-A'lā",
  'Al-Gāsyiyah',
  'Al-Fajr',
  'Al-Balad',
  'Asy-Syams',
  'Al-Lail',
  'Aḍ-Ḍuḥā',
  'Asy-Syarḥ',
  'At-Tīn',
  "Al-'Alaq",
  'Al-Qadr',
  'Al-Bayyinah',
  'Az-Zalzalah',
  "Al-'Ādiyāt",
  "Al-Qāri'ah",
  'At-Takāṡur',
  "Al-'Aṣr",
  'Al-Humazah',
  'Al-Fīl',
  'Quraisy',
  "Al-Mā'ūn",
  'Al-Kauṡar',
  'Al-Kāfirūn',
  'An-Naṣr',
  'Al-Lahab',
  'Al-Ikhlāṣ',
  'Al-Falaq',
  'An-Nās',
] as const;

export const SURAH_NAMES_ID = [
  'Al-Fatihah',
  'Al-Baqarah',
  "Ali 'Imran",
  "An-Nisa'",
  "Al-Ma'idah",
  "Al-An'am",
  "Al-A'raf",
  'Al-Anfal',
  'At-Taubah',
  'Yunus',
  'Hud',
  'Yusuf',
  "Ar-Ra'd",
  'Ibrahim',
  'Al-Hijr',
  'An-Nahl',
  "Al-Isra'",
  'Al-Kahf',
  'Maryam',
  'Taha',
  "Al-Anbiya'",
  'Al-Hajj',
  "Al-Mu'minun",
  'An-Nur',
  'Al-Furqan',
  "Asy-Syu'ara'",
  'An-Naml',
  'Al-Qasas',
  "Al-'Ankabut",
  'Ar-Rum',
  'Luqman',
  'As-Sajdah',
  'Al-Ahzab',
  "Saba'",
  'Fatir',
  'Yasin',
  'As-Saffat',
  'Sad',
  'Az-Zumar',
  'Gafir',
  'Fussilat',
  'Asy-Syura',
  'Az-Zukhruf',
  'Ad-Dukhan',
  'Al-Jasiyah',
  'Al-Ahqaf',
  'Muhammad',
  'Al-Fath',
  'Al-Hujurat',
  'Qaf',
  'Az-Zariyat',
  'At-Tur',
  'An-Najm',
  'Al-Qamar',
  'Ar-Rahman',
  "Al-Waqi'ah",
  'Al-Hadid',
  'Al-Mujadalah',
  'Al-Hasyr',
  'Al-Mumtahanah',
  'As-Saff',
  "Al-Jumu'ah",
  'Al-Munafiqun',
  'At-Tagabun',
  'At-Talaq',
  'At-tahrim',
  'Al-Mulk',
  'Al-Qalam',
  'Al-Haqqah',
  "Al-Ma'arij",
  'Nuh',
  'Al-Jinn',
  'Al-Muzzammil',
  'Al-Muddassir',
  'Al-Qiyamah',
  'Al-Insan',
  'Al-Mursalat',
  "An-Naba'",
  "An-Nazi'at",
  "'Abasa",
  'At-Takwir',
  'Al-Infitar',
  'Al-Mutaffifin',
  'Al-Insyiqaq',
  'Al-Buruj',
  'At-Tariq',
  "Al-A'la",
  'Al-Gasyiyah',
  'Al-Fajr',
  'Al-Balad',
  'Asy-Syams',
  'Al-Lail',
  'Ad-Duha',
  'Asy-Syarh',
  'At-Tin',
  "Al-'Alaq",
  'Al-Qadr',
  'Al-Bayyinah',
  'Az-Zalzalah',
  "Al-'Adiyat",
  "Al-Qari'ah",
  'At-Takasur',
  "Al-'Asr",
  'Al-Humazah',
  'Al-Fil',
  'Quraisy',
  "Al-Ma'un",
  'Al-Kausar',
  'Al-Kafirun',
  'An-Nasr',
  'Al-Lahab',
  'Al-Ikhlas',
  'Al-Falaq',
  'An-Nas',
] as const;

export const SURAH_NAMES_TRANS_ID = [
  'Pembuka',
  'Sapi',
  'Keluarga Imran',
  'Perempuan',
  'Hidangan',
  'Binatang Ternak',
  'Tempat Tertinggi',
  'Rampasan Perang',
  'Pengampunan',
  'Yunus',
  'Hud',
  'Yusuf',
  'Guruh',
  'Ibrahim',
  'Hijr',
  'Lebah',
  'Memperjalankan di Malam Hari',
  'Gua',
  'Maryam',
  'Taha',
  'Para Nabi',
  'Haji',
  'Orang-Orang Mukmin',
  'Cahaya',
  'Pembeda',
  'Para Penyair',
  'Semut',
  'Kisah-Kisah',
  'Laba-Laba',
  'Romawi',
  'Luqman',
  'Sajdah',
  'Golongan Yang Bersekutu',
  "Saba'",
  'Pencipta',
  'Yasin',
  'Barisan-Barisan',
  'Ṣād',
  'Rombongan',
  'Maha Pengampun',
  'Dijelaskan',
  'Musyawarah',
  'Perhiasan dari Emas',
  'Kabut Asap',
  'Berlutut',
  'Ahqaf',
  'Nabi Muhammad',
  'Kemenangan',
  'Kamar-Kamar',
  'Qaf',
  'Yang Menerbangkan',
  'Gunung',
  'Bintang',
  'Bulan',
  'Yang Maha Pengasih',
  'Hari Kiamat Yang Pasti Terjadi',
  'Besi',
  'Gugatan',
  'Pengusiran',
  'Wanita Yang Diuji',
  'Barisan',
  'Jumat',
  'Orang-Orang Munafik',
  'Pengungkapan Kesalahan',
  'Talak',
  'Pengharaman',
  'Kerajaan',
  'Pena',
  'Hari Kiamat Yang Pasti Terjadi',
  'Tempat-Tempat Naik',
  'Nuh',
  'Jin',
  'Orang Berkelumun',
  'Orang Berselimut',
  'Hari Kiamat',
  'Manusia',
  'Malaikat Yang Diutus',
  'Berita',
  'Yang Mencabut Dengan Keras',
  'Berwajah Masam',
  'Penggulungan',
  'Terbelah',
  'Orang-Orang Yang Curang',
  'Terbelah',
  'Gugusan Bintang',
  'Yang Datang Pada Malam Hari',
  'Yang Maha Tinggi',
  'Hari Kiamat Yang Menghilangkan Kesadaran',
  'Fajar',
  'Negeri',
  'Matahari',
  'Malam',
  'Duha',
  'Pelapangan',
  'Buah Tin',
  'Segumpal Darah',
  'Al-Qadar',
  'Bukti Nyata',
  'Guncangan',
  'Kuda Perang Yang Berlari Kencang',
  "Al-Qāri'ah",
  'Berbangga-Bangga Dalam Memperbanyak Dunia',
  'Masa',
  'Pengumpat',
  'Gajah',
  'Orang Quraisy',
  'Bantuan',
  'Nikmat Yang Banyak',
  'Orang-Orang kafir',
  'Pertolongan',
  'Gejolak Api',
  'Ikhlas',
  'Fajar',
  'Manusia',
] as const;

export const SURAH_CATEGORIES = [
  'Makkiyah',
  'Madaniyah',
  'Madaniyah',
  'Madaniyah',
  'Madaniyah',
  'Makkiyah',
  'Makkiyah',
  'Madaniyah',
  'Madaniyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Madaniyah',
  'Makkiyah',
  'Madaniyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Madaniyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Madaniyah',
  'Madaniyah',
  'Madaniyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Madaniyah',
  'Madaniyah',
  'Madaniyah',
  'Madaniyah',
  'Madaniyah',
  'Madaniyah',
  'Madaniyah',
  'Madaniyah',
  'Madaniyah',
  'Madaniyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Madaniyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Madaniyah',
  'Madaniyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Makkiyah',
  'Madaniyah',
  'Makkiyah',
  'Makkiyah',
  'Madaniyah',
  'Madaniyah',
] as const;

export const SURAH_NUM_VERSES = [
  7, 286, 200, 176, 120, 165, 206, 75, 129, 109, 123, 111, 43, 52, 99, 128, 111,
  110, 98, 135, 112, 78, 118, 64, 77, 227, 93, 88, 69, 60, 34, 30, 73, 54, 45,
  83, 182, 88, 75, 85, 54, 53, 89, 59, 37, 35, 38, 29, 18, 45, 60, 49, 62, 55,
  78, 96, 29, 22, 24, 13, 14, 11, 11, 18, 12, 12, 30, 52, 52, 44, 28, 28, 20,
  56, 40, 31, 50, 40, 46, 42, 29, 19, 36, 25, 22, 17, 19, 26, 30, 20, 15, 21,
  11, 8, 8, 19, 5, 8, 8, 11, 11, 8, 3, 9, 5, 4, 7, 3, 6, 3, 5, 4, 5, 6,
] as const;

export const SURAH_LIST = [
  {
    number: 1,
    name: 'الفاتحة',
    name_latin: 'Al-Fātiḥah',
    name_id: 'Al-Fatihah',
    name_trans_id: 'Pembuka',
    number_of_verse: 7,
    category: 'Makkiyah',
  },
  {
    number: 2,
    name: 'البقرة',
    name_latin: 'Al-Baqarah',
    name_id: 'Al-Baqarah',
    name_trans_id: 'Sapi',
    number_of_verse: 286,
    category: 'Madaniyah',
  },
  {
    number: 3,
    name: 'اٰل عمرٰن',
    name_latin: "Āli 'Imrān",
    name_id: "Ali 'Imran",
    name_trans_id: 'Keluarga Imran',
    number_of_verse: 200,
    category: 'Madaniyah',
  },
  {
    number: 4,
    name: 'النّساۤء',
    name_latin: "An-Nisā'",
    name_id: "An-Nisa'",
    name_trans_id: 'Perempuan',
    number_of_verse: 176,
    category: 'Madaniyah',
  },
  {
    number: 5,
    name: 'الماۤئدة',
    name_latin: "Al-Mā'idah",
    name_id: "Al-Ma'idah",
    name_trans_id: 'Hidangan',
    number_of_verse: 120,
    category: 'Madaniyah',
  },
  {
    number: 6,
    name: 'الانعام',
    name_latin: "Al-An'ām",
    name_id: "Al-An'am",
    name_trans_id: 'Binatang Ternak',
    number_of_verse: 165,
    category: 'Makkiyah',
  },
  {
    number: 7,
    name: 'الاعراف',
    name_latin: "Al-A'rāf",
    name_id: "Al-A'raf",
    name_trans_id: 'Tempat Tertinggi',
    number_of_verse: 206,
    category: 'Makkiyah',
  },
  {
    number: 8,
    name: 'الانفال',
    name_latin: 'Al-Anfāl',
    name_id: 'Al-Anfal',
    name_trans_id: 'Rampasan Perang',
    number_of_verse: 75,
    category: 'Madaniyah',
  },
  {
    number: 9,
    name: 'التّوبة',
    name_latin: 'At-Taubah',
    name_id: 'At-Taubah',
    name_trans_id: 'Pengampunan',
    number_of_verse: 129,
    category: 'Madaniyah',
  },
  {
    number: 10,
    name: 'يونس',
    name_latin: 'Yūnus',
    name_id: 'Yunus',
    name_trans_id: 'Yunus',
    number_of_verse: 109,
    category: 'Makkiyah',
  },
  {
    number: 11,
    name: 'هود',
    name_latin: 'Hūd',
    name_id: 'Hud',
    name_trans_id: 'Hud',
    number_of_verse: 123,
    category: 'Makkiyah',
  },
  {
    number: 12,
    name: 'يوسف',
    name_latin: 'Yūsuf',
    name_id: 'Yusuf',
    name_trans_id: 'Yusuf',
    number_of_verse: 111,
    category: 'Makkiyah',
  },
  {
    number: 13,
    name: 'الرّعد',
    name_latin: "Ar-Ra'd",
    name_id: "Ar-Ra'd",
    name_trans_id: 'Guruh',
    number_of_verse: 43,
    category: 'Makkiyah',
  },
  {
    number: 14,
    name: 'ابرٰهيم',
    name_latin: 'Ibrāhīm',
    name_id: 'Ibrahim',
    name_trans_id: 'Ibrahim',
    number_of_verse: 52,
    category: 'Makkiyah',
  },
  {
    number: 15,
    name: 'الحجر',
    name_latin: 'Al-Ḥijr',
    name_id: 'Al-Hijr',
    name_trans_id: 'Hijr',
    number_of_verse: 99,
    category: 'Makkiyah',
  },
  {
    number: 16,
    name: 'النّحل',
    name_latin: 'An-Naḥl',
    name_id: 'An-Nahl',
    name_trans_id: 'Lebah',
    number_of_verse: 128,
    category: 'Makkiyah',
  },
  {
    number: 17,
    name: 'الاسراۤء',
    name_latin: "Al-Isrā'",
    name_id: "Al-Isra'",
    name_trans_id: 'Memperjalankan di Malam Hari',
    number_of_verse: 111,
    category: 'Makkiyah',
  },
  {
    number: 18,
    name: 'الكهف',
    name_latin: 'Al-Kahf',
    name_id: 'Al-Kahf',
    name_trans_id: 'Gua',
    number_of_verse: 110,
    category: 'Makkiyah',
  },
  {
    number: 19,
    name: 'مريم',
    name_latin: 'Maryam',
    name_id: 'Maryam',
    name_trans_id: 'Maryam',
    number_of_verse: 98,
    category: 'Makkiyah',
  },
  {
    number: 20,
    name: 'طٰهٰ',
    name_latin: 'Ṭāhā',
    name_id: 'Taha',
    name_trans_id: 'Taha',
    number_of_verse: 135,
    category: 'Makkiyah',
  },
  {
    number: 21,
    name: 'الانبياۤء',
    name_latin: "Al-Anbiyā'",
    name_id: "Al-Anbiya'",
    name_trans_id: 'Para Nabi',
    number_of_verse: 112,
    category: 'Makkiyah',
  },
  {
    number: 22,
    name: 'الحجّ',
    name_latin: 'Al-Ḥajj',
    name_id: 'Al-Hajj',
    name_trans_id: 'Haji',
    number_of_verse: 78,
    category: 'Madaniyah',
  },
  {
    number: 23,
    name: 'المؤمنون',
    name_latin: "Al-Mu'minūn",
    name_id: "Al-Mu'minun",
    name_trans_id: 'Orang-Orang Mukmin',
    number_of_verse: 118,
    category: 'Makkiyah',
  },
  {
    number: 24,
    name: 'النّور',
    name_latin: 'An-Nūr',
    name_id: 'An-Nur',
    name_trans_id: 'Cahaya',
    number_of_verse: 64,
    category: 'Madaniyah',
  },
  {
    number: 25,
    name: 'الفرقان',
    name_latin: 'Al-Furqān',
    name_id: 'Al-Furqan',
    name_trans_id: 'Pembeda',
    number_of_verse: 77,
    category: 'Makkiyah',
  },
  {
    number: 26,
    name: 'الشّعراۤء',
    name_latin: "Asy-Syu'arā'",
    name_id: "Asy-Syu'ara'",
    name_trans_id: 'Para Penyair',
    number_of_verse: 227,
    category: 'Makkiyah',
  },
  {
    number: 27,
    name: 'النّمل',
    name_latin: 'An-Naml',
    name_id: 'An-Naml',
    name_trans_id: 'Semut',
    number_of_verse: 93,
    category: 'Makkiyah',
  },
  {
    number: 28,
    name: 'القصص',
    name_latin: 'Al-Qaṣaṣ',
    name_id: 'Al-Qasas',
    name_trans_id: 'Kisah-Kisah',
    number_of_verse: 88,
    category: 'Makkiyah',
  },
  {
    number: 29,
    name: 'العنكبوت',
    name_latin: "Al-'Ankabūt",
    name_id: "Al-'Ankabut",
    name_trans_id: 'Laba-Laba',
    number_of_verse: 69,
    category: 'Makkiyah',
  },
  {
    number: 30,
    name: 'الرّوم',
    name_latin: 'Ar-Rūm',
    name_id: 'Ar-Rum',
    name_trans_id: 'Romawi',
    number_of_verse: 60,
    category: 'Makkiyah',
  },
  {
    number: 31,
    name: 'لقمٰن',
    name_latin: 'Luqmān',
    name_id: 'Luqman',
    name_trans_id: 'Luqman',
    number_of_verse: 34,
    category: 'Makkiyah',
  },
  {
    number: 32,
    name: 'السّجدة',
    name_latin: 'As-Sajdah',
    name_id: 'As-Sajdah',
    name_trans_id: 'Sajdah',
    number_of_verse: 30,
    category: 'Makkiyah',
  },
  {
    number: 33,
    name: 'الاحزاب',
    name_latin: 'Al-Aḥzāb',
    name_id: 'Al-Ahzab',
    name_trans_id: 'Golongan Yang Bersekutu',
    number_of_verse: 73,
    category: 'Madaniyah',
  },
  {
    number: 34,
    name: 'سبأ',
    name_latin: "Saba'",
    name_id: "Saba'",
    name_trans_id: "Saba'",
    number_of_verse: 54,
    category: 'Makkiyah',
  },
  {
    number: 35,
    name: 'فاطر',
    name_latin: 'Fāṭir',
    name_id: 'Fatir',
    name_trans_id: 'Pencipta',
    number_of_verse: 45,
    category: 'Makkiyah',
  },
  {
    number: 36,
    name: 'يٰسۤ',
    name_latin: 'Yāsīn',
    name_id: 'Yasin',
    name_trans_id: 'Yasin',
    number_of_verse: 83,
    category: 'Makkiyah',
  },
  {
    number: 37,
    name: 'الصّٰۤفّٰت',
    name_latin: 'Aṣ-Ṣāffāt',
    name_id: 'As-Saffat',
    name_trans_id: 'Barisan-Barisan',
    number_of_verse: 182,
    category: 'Makkiyah',
  },
  {
    number: 38,
    name: 'صۤ',
    name_latin: 'Ṣād',
    name_id: 'Sad',
    name_trans_id: 'Ṣād',
    number_of_verse: 88,
    category: 'Makkiyah',
  },
  {
    number: 39,
    name: 'الزّمر',
    name_latin: 'Az-Zumar',
    name_id: 'Az-Zumar',
    name_trans_id: 'Rombongan',
    number_of_verse: 75,
    category: 'Makkiyah',
  },
  {
    number: 40,
    name: 'غافر',
    name_latin: 'Gāfir',
    name_id: 'Gafir',
    name_trans_id: 'Maha Pengampun',
    number_of_verse: 85,
    category: 'Makkiyah',
  },
  {
    number: 41,
    name: 'فصّلت',
    name_latin: 'Fuṣṣilat',
    name_id: 'Fussilat',
    name_trans_id: 'Dijelaskan',
    number_of_verse: 54,
    category: 'Makkiyah',
  },
  {
    number: 42,
    name: 'الشّورٰى',
    name_latin: 'Asy-Syūrā',
    name_id: 'Asy-Syura',
    name_trans_id: 'Musyawarah',
    number_of_verse: 53,
    category: 'Makkiyah',
  },
  {
    number: 43,
    name: 'الزّخرف',
    name_latin: 'Az-Zukhruf',
    name_id: 'Az-Zukhruf',
    name_trans_id: 'Perhiasan dari Emas',
    number_of_verse: 89,
    category: 'Makkiyah',
  },
  {
    number: 44,
    name: 'الدّخان',
    name_latin: 'Ad-Dukhān',
    name_id: 'Ad-Dukhan',
    name_trans_id: 'Kabut Asap',
    number_of_verse: 59,
    category: 'Makkiyah',
  },
  {
    number: 45,
    name: 'الجاثية',
    name_latin: 'Al-Jāṡiyah',
    name_id: 'Al-Jasiyah',
    name_trans_id: 'Berlutut',
    number_of_verse: 37,
    category: 'Makkiyah',
  },
  {
    number: 46,
    name: 'الاحقاف',
    name_latin: 'Al-Aḥqāf',
    name_id: 'Al-Ahqaf',
    name_trans_id: 'Ahqaf',
    number_of_verse: 35,
    category: 'Makkiyah',
  },
  {
    number: 47,
    name: 'محمّد',
    name_latin: 'Muḥammad',
    name_id: 'Muhammad',
    name_trans_id: 'Nabi Muhammad',
    number_of_verse: 38,
    category: 'Madaniyah',
  },
  {
    number: 48,
    name: 'الفتح',
    name_latin: 'Al-Fatḥ',
    name_id: 'Al-Fath',
    name_trans_id: 'Kemenangan',
    number_of_verse: 29,
    category: 'Madaniyah',
  },
  {
    number: 49,
    name: 'الحجرٰت',
    name_latin: 'Al-Ḥujurāt',
    name_id: 'Al-Hujurat',
    name_trans_id: 'Kamar-Kamar',
    number_of_verse: 18,
    category: 'Madaniyah',
  },
  {
    number: 50,
    name: 'قۤ',
    name_latin: 'Qāf',
    name_id: 'Qaf',
    name_trans_id: 'Qaf',
    number_of_verse: 45,
    category: 'Makkiyah',
  },
  {
    number: 51,
    name: 'الذّٰريٰت',
    name_latin: 'Aż-Żāriyāt',
    name_id: 'Az-Zariyat',
    name_trans_id: 'Yang Menerbangkan',
    number_of_verse: 60,
    category: 'Makkiyah',
  },
  {
    number: 52,
    name: 'الطّور',
    name_latin: 'Aṭ-Ṭūr',
    name_id: 'At-Tur',
    name_trans_id: 'Gunung',
    number_of_verse: 49,
    category: 'Makkiyah',
  },
  {
    number: 53,
    name: 'النّجم',
    name_latin: 'An-Najm',
    name_id: 'An-Najm',
    name_trans_id: 'Bintang',
    number_of_verse: 62,
    category: 'Makkiyah',
  },
  {
    number: 54,
    name: 'القمر',
    name_latin: 'Al-Qamar',
    name_id: 'Al-Qamar',
    name_trans_id: 'Bulan',
    number_of_verse: 55,
    category: 'Makkiyah',
  },
  {
    number: 55,
    name: 'الرّحمٰن',
    name_latin: 'Ar-Raḥmān',
    name_id: 'Ar-Rahman',
    name_trans_id: 'Yang Maha Pengasih',
    number_of_verse: 78,
    category: 'Makkiyah',
  },
  {
    number: 56,
    name: 'الواقعة',
    name_latin: "Al-Wāqi'ah",
    name_id: "Al-Waqi'ah",
    name_trans_id: 'Hari Kiamat Yang Pasti Terjadi',
    number_of_verse: 96,
    category: 'Makkiyah',
  },
  {
    number: 57,
    name: 'الحديد',
    name_latin: 'Al-Ḥadīd',
    name_id: 'Al-Hadid',
    name_trans_id: 'Besi',
    number_of_verse: 29,
    category: 'Madaniyah',
  },
  {
    number: 58,
    name: 'المجادلة',
    name_latin: 'Al-Mujādalah',
    name_id: 'Al-Mujadalah',
    name_trans_id: 'Gugatan',
    number_of_verse: 22,
    category: 'Madaniyah',
  },
  {
    number: 59,
    name: 'الحشر',
    name_latin: 'Al-Ḥasyr',
    name_id: 'Al-Hasyr',
    name_trans_id: 'Pengusiran',
    number_of_verse: 24,
    category: 'Madaniyah',
  },
  {
    number: 60,
    name: 'الممتحنة',
    name_latin: 'Al-Mumtaḥanah',
    name_id: 'Al-Mumtahanah',
    name_trans_id: 'Wanita Yang Diuji',
    number_of_verse: 13,
    category: 'Madaniyah',
  },
  {
    number: 61,
    name: 'الصّفّ',
    name_latin: 'Aṣ-Ṣaff',
    name_id: 'As-Saff',
    name_trans_id: 'Barisan',
    number_of_verse: 14,
    category: 'Madaniyah',
  },
  {
    number: 62,
    name: 'الجمعة',
    name_latin: "Al-Jumu'ah",
    name_id: "Al-Jumu'ah",
    name_trans_id: 'Jumat',
    number_of_verse: 11,
    category: 'Madaniyah',
  },
  {
    number: 63,
    name: 'المنٰفقون',
    name_latin: 'Al-Munāfiqūn',
    name_id: 'Al-Munafiqun',
    name_trans_id: 'Orang-Orang Munafik',
    number_of_verse: 11,
    category: 'Madaniyah',
  },
  {
    number: 64,
    name: 'التّغابن',
    name_latin: 'At-Tagābun',
    name_id: 'At-Tagabun',
    name_trans_id: 'Pengungkapan Kesalahan',
    number_of_verse: 18,
    category: 'Madaniyah',
  },
  {
    number: 65,
    name: 'الطّلاق',
    name_latin: 'Aṭ-Ṭalāq',
    name_id: 'At-Talaq',
    name_trans_id: 'Talak',
    number_of_verse: 12,
    category: 'Madaniyah',
  },
  {
    number: 66,
    name: 'التّحريم',
    name_latin: 'At-taḥrīm',
    name_id: 'At-tahrim',
    name_trans_id: 'Pengharaman',
    number_of_verse: 12,
    category: 'Madaniyah',
  },
  {
    number: 67,
    name: 'المُلك',
    name_latin: 'Al-Mulk',
    name_id: 'Al-Mulk',
    name_trans_id: 'Kerajaan',
    number_of_verse: 30,
    category: 'Makkiyah',
  },
  {
    number: 68,
    name: 'القلم',
    name_latin: 'Al-Qalam',
    name_id: 'Al-Qalam',
    name_trans_id: 'Pena',
    number_of_verse: 52,
    category: 'Makkiyah',
  },
  {
    number: 69,
    name: 'الحاۤقّة',
    name_latin: 'Al-Ḥāqqah',
    name_id: 'Al-Haqqah',
    name_trans_id: 'Hari Kiamat Yang Pasti Terjadi',
    number_of_verse: 52,
    category: 'Makkiyah',
  },
  {
    number: 70,
    name: 'المعارج',
    name_latin: "Al-Ma'ārij",
    name_id: "Al-Ma'arij",
    name_trans_id: 'Tempat-Tempat Naik',
    number_of_verse: 44,
    category: 'Makkiyah',
  },
  {
    number: 71,
    name: 'نوح',
    name_latin: 'Nūḥ',
    name_id: 'Nuh',
    name_trans_id: 'Nuh',
    number_of_verse: 28,
    category: 'Makkiyah',
  },
  {
    number: 72,
    name: 'الجنّ',
    name_latin: 'Al-Jinn',
    name_id: 'Al-Jinn',
    name_trans_id: 'Jin',
    number_of_verse: 28,
    category: 'Makkiyah',
  },
  {
    number: 73,
    name: 'المزّمّل',
    name_latin: 'Al-Muzzammil',
    name_id: 'Al-Muzzammil',
    name_trans_id: 'Orang Berkelumun',
    number_of_verse: 20,
    category: 'Makkiyah',
  },
  {
    number: 74,
    name: 'المدّثّر',
    name_latin: 'Al-Muddaṡṡir',
    name_id: 'Al-Muddassir',
    name_trans_id: 'Orang Berselimut',
    number_of_verse: 56,
    category: 'Makkiyah',
  },
  {
    number: 75,
    name: 'القيٰمة',
    name_latin: 'Al-Qiyāmah',
    name_id: 'Al-Qiyamah',
    name_trans_id: 'Hari Kiamat',
    number_of_verse: 40,
    category: 'Makkiyah',
  },
  {
    number: 76,
    name: 'الانسان',
    name_latin: 'Al-Insān',
    name_id: 'Al-Insan',
    name_trans_id: 'Manusia',
    number_of_verse: 31,
    category: 'Madaniyah',
  },
  {
    number: 77,
    name: 'المرسلٰت',
    name_latin: 'Al-Mursalāt',
    name_id: 'Al-Mursalat',
    name_trans_id: 'Malaikat Yang Diutus',
    number_of_verse: 50,
    category: 'Makkiyah',
  },
  {
    number: 78,
    name: 'النّبأ',
    name_latin: "An-Naba'",
    name_id: "An-Naba'",
    name_trans_id: 'Berita',
    number_of_verse: 40,
    category: 'Makkiyah',
  },
  {
    number: 79,
    name: 'النّٰزعٰت',
    name_latin: "An-Nāzi'āt",
    name_id: "An-Nazi'at",
    name_trans_id: 'Yang Mencabut Dengan Keras',
    number_of_verse: 46,
    category: 'Makkiyah',
  },
  {
    number: 80,
    name: 'عبس',
    name_latin: "'Abasa",
    name_id: "'Abasa",
    name_trans_id: 'Berwajah Masam',
    number_of_verse: 42,
    category: 'Makkiyah',
  },
  {
    number: 81,
    name: 'التّكوير',
    name_latin: 'At-Takwīr',
    name_id: 'At-Takwir',
    name_trans_id: 'Penggulungan',
    number_of_verse: 29,
    category: 'Makkiyah',
  },
  {
    number: 82,
    name: 'الانفطار',
    name_latin: 'Al-Infiṭār',
    name_id: 'Al-Infitar',
    name_trans_id: 'Terbelah',
    number_of_verse: 19,
    category: 'Makkiyah',
  },
  {
    number: 83,
    name: 'المطفّفين',
    name_latin: 'Al-Muṭaffifīn',
    name_id: 'Al-Mutaffifin',
    name_trans_id: 'Orang-Orang Yang Curang',
    number_of_verse: 36,
    category: 'Makkiyah',
  },
  {
    number: 84,
    name: 'الانشقاق',
    name_latin: 'Al-Insyiqāq',
    name_id: 'Al-Insyiqaq',
    name_trans_id: 'Terbelah',
    number_of_verse: 25,
    category: 'Makkiyah',
  },
  {
    number: 85,
    name: 'البروج',
    name_latin: 'Al-Burūj',
    name_id: 'Al-Buruj',
    name_trans_id: 'Gugusan Bintang',
    number_of_verse: 22,
    category: 'Makkiyah',
  },
  {
    number: 86,
    name: 'الطّارق',
    name_latin: 'Aṭ-Ṭāriq',
    name_id: 'At-Tariq',
    name_trans_id: 'Yang Datang Pada Malam Hari',
    number_of_verse: 17,
    category: 'Makkiyah',
  },
  {
    number: 87,
    name: 'الاعلى',
    name_latin: "Al-A'lā",
    name_id: "Al-A'la",
    name_trans_id: 'Yang Maha Tinggi',
    number_of_verse: 19,
    category: 'Makkiyah',
  },
  {
    number: 88,
    name: 'الغاشية',
    name_latin: 'Al-Gāsyiyah',
    name_id: 'Al-Gasyiyah',
    name_trans_id: 'Hari Kiamat Yang Menghilangkan Kesadaran',
    number_of_verse: 26,
    category: 'Makkiyah',
  },
  {
    number: 89,
    name: 'الفجر',
    name_latin: 'Al-Fajr',
    name_id: 'Al-Fajr',
    name_trans_id: 'Fajar',
    number_of_verse: 30,
    category: 'Makkiyah',
  },
  {
    number: 90,
    name: 'البلد',
    name_latin: 'Al-Balad',
    name_id: 'Al-Balad',
    name_trans_id: 'Negeri',
    number_of_verse: 20,
    category: 'Makkiyah',
  },
  {
    number: 91,
    name: 'الشّمس',
    name_latin: 'Asy-Syams',
    name_id: 'Asy-Syams',
    name_trans_id: 'Matahari',
    number_of_verse: 15,
    category: 'Makkiyah',
  },
  {
    number: 92,
    name: 'الّيل',
    name_latin: 'Al-Lail',
    name_id: 'Al-Lail',
    name_trans_id: 'Malam',
    number_of_verse: 21,
    category: 'Makkiyah',
  },
  {
    number: 93,
    name: 'الضّحى',
    name_latin: 'Aḍ-Ḍuḥā',
    name_id: 'Ad-Duha',
    name_trans_id: 'Duha',
    number_of_verse: 11,
    category: 'Makkiyah',
  },
  {
    number: 94,
    name: 'الشّرح',
    name_latin: 'Asy-Syarḥ',
    name_id: 'Asy-Syarh',
    name_trans_id: 'Pelapangan',
    number_of_verse: 8,
    category: 'Makkiyah',
  },
  {
    number: 95,
    name: 'التّين',
    name_latin: 'At-Tīn',
    name_id: 'At-Tin',
    name_trans_id: 'Buah Tin',
    number_of_verse: 8,
    category: 'Makkiyah',
  },
  {
    number: 96,
    name: 'العلق',
    name_latin: "Al-'Alaq",
    name_id: "Al-'Alaq",
    name_trans_id: 'Segumpal Darah',
    number_of_verse: 19,
    category: 'Makkiyah',
  },
  {
    number: 97,
    name: 'القدر',
    name_latin: 'Al-Qadr',
    name_id: 'Al-Qadr',
    name_trans_id: 'Al-Qadar',
    number_of_verse: 5,
    category: 'Makkiyah',
  },
  {
    number: 98,
    name: 'البيّنة',
    name_latin: 'Al-Bayyinah',
    name_id: 'Al-Bayyinah',
    name_trans_id: 'Bukti Nyata',
    number_of_verse: 8,
    category: 'Madaniyah',
  },
  {
    number: 99,
    name: 'الزّلزلة',
    name_latin: 'Az-Zalzalah',
    name_id: 'Az-Zalzalah',
    name_trans_id: 'Guncangan',
    number_of_verse: 8,
    category: 'Madaniyah',
  },
  {
    number: 100,
    name: 'العٰديٰت',
    name_latin: "Al-'Ādiyāt",
    name_id: "Al-'Adiyat",
    name_trans_id: 'Kuda Perang Yang Berlari Kencang',
    number_of_verse: 11,
    category: 'Makkiyah',
  },
  {
    number: 101,
    name: 'القارعة',
    name_latin: "Al-Qāri'ah",
    name_id: "Al-Qari'ah",
    name_trans_id: "Al-Qāri'ah",
    number_of_verse: 11,
    category: 'Makkiyah',
  },
  {
    number: 102,
    name: 'التّكاثر',
    name_latin: 'At-Takāṡur',
    name_id: 'At-Takasur',
    name_trans_id: 'Berbangga-Bangga Dalam Memperbanyak Dunia',
    number_of_verse: 8,
    category: 'Makkiyah',
  },
  {
    number: 103,
    name: 'العصر',
    name_latin: "Al-'Aṣr",
    name_id: "Al-'Asr",
    name_trans_id: 'Masa',
    number_of_verse: 3,
    category: 'Makkiyah',
  },
  {
    number: 104,
    name: 'الهمزة',
    name_latin: 'Al-Humazah',
    name_id: 'Al-Humazah',
    name_trans_id: 'Pengumpat',
    number_of_verse: 9,
    category: 'Makkiyah',
  },
  {
    number: 105,
    name: 'الفيل',
    name_latin: 'Al-Fīl',
    name_id: 'Al-Fil',
    name_trans_id: 'Gajah',
    number_of_verse: 5,
    category: 'Makkiyah',
  },
  {
    number: 106,
    name: 'قريش',
    name_latin: 'Quraisy',
    name_id: 'Quraisy',
    name_trans_id: 'Orang Quraisy',
    number_of_verse: 4,
    category: 'Makkiyah',
  },
  {
    number: 107,
    name: 'الماعون',
    name_latin: "Al-Mā'ūn",
    name_id: "Al-Ma'un",
    name_trans_id: 'Bantuan',
    number_of_verse: 7,
    category: 'Makkiyah',
  },
  {
    number: 108,
    name: 'الكوثر',
    name_latin: 'Al-Kauṡar',
    name_id: 'Al-Kausar',
    name_trans_id: 'Nikmat Yang Banyak',
    number_of_verse: 3,
    category: 'Makkiyah',
  },
  {
    number: 109,
    name: 'الكٰفرون',
    name_latin: 'Al-Kāfirūn',
    name_id: 'Al-Kafirun',
    name_trans_id: 'Orang-Orang kafir',
    number_of_verse: 6,
    category: 'Makkiyah',
  },
  {
    number: 110,
    name: 'النّصر',
    name_latin: 'An-Naṣr',
    name_id: 'An-Nasr',
    name_trans_id: 'Pertolongan',
    number_of_verse: 3,
    category: 'Madaniyah',
  },
  {
    number: 111,
    name: 'اللّهب',
    name_latin: 'Al-Lahab',
    name_id: 'Al-Lahab',
    name_trans_id: 'Gejolak Api',
    number_of_verse: 5,
    category: 'Makkiyah',
  },
  {
    number: 112,
    name: 'الاخلاص',
    name_latin: 'Al-Ikhlāṣ',
    name_id: 'Al-Ikhlas',
    name_trans_id: 'Ikhlas',
    number_of_verse: 4,
    category: 'Makkiyah',
  },
  {
    number: 113,
    name: 'الفلق',
    name_latin: 'Al-Falaq',
    name_id: 'Al-Falaq',
    name_trans_id: 'Fajar',
    number_of_verse: 5,
    category: 'Madaniyah',
  },
  {
    number: 114,
    name: 'النّاس',
    name_latin: 'An-Nās',
    name_id: 'An-Nas',
    name_trans_id: 'Manusia',
    number_of_verse: 6,
    category: 'Madaniyah',
  },
];
